/*
 * ============================================================================
 * Licensed Materials - Property of IBM
 * Project  Zero
 *
 * (C) Copyright IBM Corp. 2007  All Rights Reserved.
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp.
 * ============================================================================
 * Copyright (c) 1999 - 2006 The PHP Group. All rights reserved.
 * ============================================================================
 */
package com.ibm.p8.engine.parser.core;

//////////////////////////////////////////////////////////////////
//                                                              //
//   This file was auto-generated by the LPG Eclipse Tooling.   //
//   It is safe to edit this file. It will not be overwritten.  //
//                                                              //
//////////////////////////////////////////////////////////////////
					

/**
  * Based on the LEG examples shipped with JikesPG
 *
 * @author Chris Laffra 
 */
public interface LexerSymbols {
    public static final int
    Char_CtlCharNotNL = 1,
    Char_Blank = 2,
    Char_NL = 3,
    Char_a = 17,
    Char_b = 36,
    Char_c = 37,
    Char_d = 18,
    Char_e = 4,
    Char_f = 23,
    Char_g = 38,
    Char_h = 19,
    Char_i = 20,
    Char_j = 39,
    Char_k = 21,
    Char_l = 15,
    Char_m = 40,
    Char_n = 16,
    Char_o = 24,
    Char_p = 41,
    Char_q = 42,
    Char_r = 25,
    Char_s = 22,
    Char_t = 43,
    Char_u = 44,
    Char_v = 45,
    Char_w = 46,
    Char_x = 47,
    Char_y = 48,
    Char_z = 49,
    Char__ = 50,
    Char_0 = 26,
    Char_1 = 27,
    Char_2 = 28,
    Char_3 = 29,
    Char_4 = 30,
    Char_5 = 31,
    Char_6 = 32,
    Char_7 = 33,
    Char_8 = 34,
    Char_9 = 35,
    Char_Plus = 7,
    Char_Minus = 8,
    Char_Slash = 5,
    Char_Star = 6,
    Char_LeftParen = 9,
    Char_RightParen = 10,
    Char_Equal = 11,
    Char_DoubleQuote = 52,
    Char_AtSign = 53,
    Char_BackQuote = 54,
    Char_Tilde = 55,
    Char_Exclaimation = 56,
    Char_Sharp = 57,
    Char_DollarSign = 58,
    Char_Percent = 59,
    Char_Ampersand = 60,
    Char_Caret = 61,
    Char_Colon = 62,
    Char_SemiColon = 12,
    Char_SingleQuote = 63,
    Char_BackSlash = 64,
    Char_VerticalBar = 65,
    Char_LeftBrace = 66,
    Char_RightBrace = 67,
    Char_LeftBracket = 13,
    Char_RightBracket = 14,
    Char_QuestionMark = 68,
    Char_Comma = 69,
    Char_Dot = 70,
    Char_LessThan = 71,
    Char_GreaterThan = 72,
    Char_AfterASCII = 51,
    Char_EOF = 73,

    NUM_TOKENS = 73;

    public static final boolean isValidForParser = true;
}

