/*
 * ============================================================================
 * Licensed Materials - Property of IBM
 * Project  Zero
 *
 * (C) Copyright IBM Corp. 2007  All Rights Reserved.
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp.
 * ============================================================================
 * Copyright (c) 1999 - 2006 The PHP Group. All rights reserved.
 * ============================================================================
 */
package com.ibm.p8.engine.parser.core;

public interface PHPParsersym {
    public static final int
      T_INCLUDE = 44 , 
      T_INCLUDE_ONCE = 45 , 
      T_EVAL = 46 , 
      T_REQUIRE = 47 , 
      T_REQUIRE_ONCE = 48 , 
      T_COMMA = 77 , 
      T_LOGICAL_OR = 110 , 
      T_LOGICAL_XOR = 111 , 
      T_LOGICAL_AND = 112 , 
      T_PRINT = 49 , 
      T_EQUAL = 10 , 
      T_PLUS_EQUAL = 11 , 
      T_MINUS_EQUAL = 12 , 
      T_MUL_EQUAL = 13 , 
      T_DIV_EQUAL = 14 , 
      T_CONCAT_EQUAL = 15 , 
      T_MOD_EQUAL = 16 , 
      T_AND_EQUAL = 17 , 
      T_OR_EQUAL = 18 , 
      T_XOR_EQUAL = 19 , 
      T_SL_EQUAL = 20 , 
      T_SR_EQUAL = 21 , 
      T_QUESTION = 78 , 
      T_COLON = 72 , 
      T_BOOLEAN_OR = 79 , 
      T_BOOLEAN_AND = 73 , 
      T_VERTICAL_LINE = 69 , 
      T_CARET = 67 , 
      T_AMPERSAND = 22 , 
      T_IS_EQUAL = 113 , 
      T_IS_NOT_EQUAL = 114 , 
      T_SHR_EQUAL = 115 , 
      T_IS_IDENTICAL = 116 , 
      T_IS_NOT_IDENTICAL = 117 , 
      T_LT = 118 , 
      T_IS_SMALLER_OR_EQUAL = 119 , 
      T_GT = 120 , 
      T_IS_GREATER_OR_EQUAL = 121 , 
      T_SL = 26 , 
      T_SR = 27 , 
      T_PLUS = 2 , 
      T_MINUS = 3 , 
      T_PERIOD = 28 , 
      T_ASTERISK = 23 , 
      T_SLASH = 24 , 
      T_PERCENT = 25 , 
      T_EXCLAMATION = 50 , 
      T_INSTANCEOF = 122 , 
      T_TILDE = 51 , 
      T_INC = 4 , 
      T_DEC = 5 , 
      T_INT_CAST = 52 , 
      T_DOUBLE_CAST = 53 , 
      T_STRING_CAST = 54 , 
      T_ARRAY_CAST = 55 , 
      T_OBJECT_CAST = 56 , 
      T_BOOL_CAST = 57 , 
      T_UNSET_CAST = 58 , 
      T_FLOAT_CAST = 59 , 
      T_AT_MARK = 60 , 
      T_BRACKET_OPEN = 80 , 
      T_NEW = 33 , 
      T_CLONE = 61 , 
      T_EXIT = 62 , 
      T_DIE = 63 , 
      T_IF = 81 , 
      T_ELSEIF = 123 , 
      T_ELSE = 124 , 
      T_ENDIF = 125 , 
      T_LNUMBER = 29 , 
      T_DNUMBER = 30 , 
      T_STRING = 7 , 
      T_STRING_VARNAME = 64 , 
      T_VARIABLE = 1 , 
      T_NUM_STRING = 126 , 
      T_INLINE_HTML = 82 , 
      T_CHARACTER = 145 , 
      T_BAD_CHARACTER = 146 , 
      T_ENCAPSED_AND_WHITESPACE = 68 , 
      T_CONSTANT_ENCAPSED_STRING = 70 , 
      T_ECHO = 83 , 
      T_DO = 84 , 
      T_WHILE = 74 , 
      T_ENDWHILE = 127 , 
      T_FOR = 85 , 
      T_ENDFOR = 128 , 
      T_FOREACH = 86 , 
      T_ENDFOREACH = 129 , 
      T_DECLARE = 87 , 
      T_ENDDECLARE = 130 , 
      T_AS = 101 , 
      T_SWITCH = 88 , 
      T_ENDSWITCH = 131 , 
      T_CASE = 102 , 
      T_DEFAULT = 103 , 
      T_BREAK = 89 , 
      T_CONTINUE = 90 , 
      T_FUNCTION = 104 , 
      T_CONST = 132 , 
      T_RETURN = 91 , 
      T_TRY = 92 , 
      T_CATCH = 133 , 
      T_THROW = 93 , 
      T_USE = 94 , 
      T_GLOBAL = 95 , 
      T_STATIC = 71 , 
      T_ABSTRACT = 96 , 
      T_FINAL = 97 , 
      T_PRIVATE = 105 , 
      T_PROTECTED = 106 , 
      T_PUBLIC = 107 , 
      T_VAR = 134 , 
      T_UNSET = 98 , 
      T_ISSET = 65 , 
      T_EMPTY = 66 , 
      T_HALT_COMPILER = 135 , 
      T_CLASS = 108 , 
      T_INTERFACE = 136 , 
      T_EXTENDS = 137 , 
      T_IMPLEMENTS = 138 , 
      T_OBJECT_OPERATOR = 109 , 
      T_DOUBLE_ARROW = 139 , 
      T_LIST = 34 , 
      T_ARRAY = 31 , 
      T_CLASS_C = 35 , 
      T_METHOD_C = 36 , 
      T_FUNC_C = 37 , 
      T_LINE_C = 38 , 
      T_FILE_C = 39 , 
      T_COMMENT = 147 , 
      T_DOC_COMMENT = 140 , 
      T_OPEN_TAG = 148 , 
      T_OPEN_TAG_WITH_ECHO = 149 , 
      T_CLOSE_TAG = 150 , 
      T_WHITESPACE = 151 , 
      T_START_HEREDOC = 141 , 
      T_END_HEREDOC = 142 , 
      T_DOLLAR_OPEN_CURLY_BRACES = 6 , 
      T_CURLY_OPEN = 9 , 
      T_PAAMAYIM_NEKUDOTAYIM = 143 , 
      T_SEMICOLON = 40 , 
      T_LPAR = 32 , 
      T_RPAR = 99 , 
      T_CURLY_CLOSE = 100 , 
      T_BRACKET_CLOSE = 144 , 
      T_DOUBLE_QUOTE = 75 , 
      T_SINGLE_QUOTE = 76 , 
      T_BACK_QUOTE = 41 , 
      T_DOLLAR = 8 , 
      T_BINARY = 42 , 
      T_LOWER_BINARY = 43 , 
      $eof = 152 , 
      $error = 153 , 

      NUM_TOKENS = 153;

      public static final String[] orderedTerminalSymbols = {
                 "" , 
                 "T_VARIABLE" , 
                 "T_PLUS" , 
                 "T_MINUS" , 
                 "T_INC" , 
                 "T_DEC" , 
                 "T_DOLLAR_OPEN_CURLY_BRACES" , 
                 "T_STRING" , 
                 "T_DOLLAR" , 
                 "T_CURLY_OPEN" , 
                 "T_EQUAL" , 
                 "T_PLUS_EQUAL" , 
                 "T_MINUS_EQUAL" , 
                 "T_MUL_EQUAL" , 
                 "T_DIV_EQUAL" , 
                 "T_CONCAT_EQUAL" , 
                 "T_MOD_EQUAL" , 
                 "T_AND_EQUAL" , 
                 "T_OR_EQUAL" , 
                 "T_XOR_EQUAL" , 
                 "T_SL_EQUAL" , 
                 "T_SR_EQUAL" , 
                 "T_AMPERSAND" , 
                 "T_ASTERISK" , 
                 "T_SLASH" , 
                 "T_PERCENT" , 
                 "T_SL" , 
                 "T_SR" , 
                 "T_PERIOD" , 
                 "T_LNUMBER" , 
                 "T_DNUMBER" , 
                 "T_ARRAY" , 
                 "T_LPAR" , 
                 "T_NEW" , 
                 "T_LIST" , 
                 "T_CLASS_C" , 
                 "T_METHOD_C" , 
                 "T_FUNC_C" , 
                 "T_LINE_C" , 
                 "T_FILE_C" , 
                 "T_SEMICOLON" , 
                 "T_BACK_QUOTE" , 
                 "T_BINARY" , 
                 "T_LOWER_BINARY" , 
                 "T_INCLUDE" , 
                 "T_INCLUDE_ONCE" , 
                 "T_EVAL" , 
                 "T_REQUIRE" , 
                 "T_REQUIRE_ONCE" , 
                 "T_PRINT" , 
                 "T_EXCLAMATION" , 
                 "T_TILDE" , 
                 "T_INT_CAST" , 
                 "T_DOUBLE_CAST" , 
                 "T_STRING_CAST" , 
                 "T_ARRAY_CAST" , 
                 "T_OBJECT_CAST" , 
                 "T_BOOL_CAST" , 
                 "T_UNSET_CAST" , 
                 "T_FLOAT_CAST" , 
                 "T_AT_MARK" , 
                 "T_CLONE" , 
                 "T_EXIT" , 
                 "T_DIE" , 
                 "T_STRING_VARNAME" , 
                 "T_ISSET" , 
                 "T_EMPTY" , 
                 "T_CARET" , 
                 "T_ENCAPSED_AND_WHITESPACE" , 
                 "T_VERTICAL_LINE" , 
                 "T_CONSTANT_ENCAPSED_STRING" , 
                 "T_STATIC" , 
                 "T_COLON" , 
                 "T_BOOLEAN_AND" , 
                 "T_WHILE" , 
                 "T_DOUBLE_QUOTE" , 
                 "T_SINGLE_QUOTE" , 
                 "T_COMMA" , 
                 "T_QUESTION" , 
                 "T_BOOLEAN_OR" , 
                 "T_BRACKET_OPEN" , 
                 "T_IF" , 
                 "T_INLINE_HTML" , 
                 "T_ECHO" , 
                 "T_DO" , 
                 "T_FOR" , 
                 "T_FOREACH" , 
                 "T_DECLARE" , 
                 "T_SWITCH" , 
                 "T_BREAK" , 
                 "T_CONTINUE" , 
                 "T_RETURN" , 
                 "T_TRY" , 
                 "T_THROW" , 
                 "T_USE" , 
                 "T_GLOBAL" , 
                 "T_ABSTRACT" , 
                 "T_FINAL" , 
                 "T_UNSET" , 
                 "T_RPAR" , 
                 "T_CURLY_CLOSE" , 
                 "T_AS" , 
                 "T_CASE" , 
                 "T_DEFAULT" , 
                 "T_FUNCTION" , 
                 "T_PRIVATE" , 
                 "T_PROTECTED" , 
                 "T_PUBLIC" , 
                 "T_CLASS" , 
                 "T_OBJECT_OPERATOR" , 
                 "T_LOGICAL_OR" , 
                 "T_LOGICAL_XOR" , 
                 "T_LOGICAL_AND" , 
                 "T_IS_EQUAL" , 
                 "T_IS_NOT_EQUAL" , 
                 "T_SHR_EQUAL" , 
                 "T_IS_IDENTICAL" , 
                 "T_IS_NOT_IDENTICAL" , 
                 "T_LT" , 
                 "T_IS_SMALLER_OR_EQUAL" , 
                 "T_GT" , 
                 "T_IS_GREATER_OR_EQUAL" , 
                 "T_INSTANCEOF" , 
                 "T_ELSEIF" , 
                 "T_ELSE" , 
                 "T_ENDIF" , 
                 "T_NUM_STRING" , 
                 "T_ENDWHILE" , 
                 "T_ENDFOR" , 
                 "T_ENDFOREACH" , 
                 "T_ENDDECLARE" , 
                 "T_ENDSWITCH" , 
                 "T_CONST" , 
                 "T_CATCH" , 
                 "T_VAR" , 
                 "T_HALT_COMPILER" , 
                 "T_INTERFACE" , 
                 "T_EXTENDS" , 
                 "T_IMPLEMENTS" , 
                 "T_DOUBLE_ARROW" , 
                 "T_DOC_COMMENT" , 
                 "T_START_HEREDOC" , 
                 "T_END_HEREDOC" , 
                 "T_PAAMAYIM_NEKUDOTAYIM" , 
                 "T_BRACKET_CLOSE" , 
                 "T_CHARACTER" , 
                 "T_BAD_CHARACTER" , 
                 "T_COMMENT" , 
                 "T_OPEN_TAG" , 
                 "T_OPEN_TAG_WITH_ECHO" , 
                 "T_CLOSE_TAG" , 
                 "T_WHITESPACE" , 
                 "$eof" , 
                 "$error"
             };

    public static final boolean isValidForParser = true;
}
