/*
 * ============================================================================
 * Licensed Materials - Property of IBM
 * Project  Zero
 *
 * (C) Copyright IBM Corp. 2007  All Rights Reserved.
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp.
 * ============================================================================
 * Copyright (c) 1999 - 2006 The PHP Group. All rights reserved.
 * ============================================================================
 */
package com.ibm.p8.engine.parser.core;


//////////////////////////////////////////////////////////////////
//                                                              //
//   This file was auto-generated by the LPG Eclipse Tooling.   //
//   It is safe to edit this file. It will not be overwritten.  //
//                                                              //
//////////////////////////////////////////////////////////////////
					

/**
 * Based on the LEG examples shipped with JikesPG.
 *
 */
interface TokenKindMap extends LexerSymbols {
	 
	 int[] TOKENKIND = { 
		    Char_CtlCharNotNL,
			Char_CtlCharNotNL, Char_CtlCharNotNL, Char_CtlCharNotNL,
			Char_CtlCharNotNL, Char_CtlCharNotNL, Char_CtlCharNotNL,
			Char_CtlCharNotNL, Char_CtlCharNotNL, Char_CtlCharNotNL, Char_NL,
			Char_CtlCharNotNL, Char_CtlCharNotNL, Char_CtlCharNotNL,
			Char_CtlCharNotNL, Char_CtlCharNotNL, Char_CtlCharNotNL,
			Char_CtlCharNotNL, Char_CtlCharNotNL, Char_CtlCharNotNL,
			Char_CtlCharNotNL, Char_CtlCharNotNL, Char_CtlCharNotNL,
			Char_CtlCharNotNL, Char_CtlCharNotNL, Char_CtlCharNotNL,
			Char_CtlCharNotNL, Char_CtlCharNotNL, Char_CtlCharNotNL,
			Char_CtlCharNotNL, Char_CtlCharNotNL, Char_CtlCharNotNL,
			Char_Blank, Char_Exclaimation, Char_DoubleQuote, Char_Sharp,
			Char_DollarSign, Char_Percent, Char_Ampersand, Char_SingleQuote,
			Char_LeftParen, Char_RightParen, Char_Star, Char_Plus, Char_Comma,
			Char_Minus, Char_Dot, Char_Slash, Char_0, Char_1, Char_2, Char_3,
			Char_4, Char_5, Char_6, Char_7, Char_8, Char_9, Char_Colon,
			Char_SemiColon, Char_LessThan, Char_Equal, Char_GreaterThan,
			Char_QuestionMark, Char_AtSign, Char_a, Char_b, Char_c, Char_d,
			Char_e, Char_f, Char_g, Char_h, Char_i, Char_j, Char_k, Char_l,
			Char_m, Char_n, Char_o, Char_p, Char_q, Char_r, Char_s, Char_t,
			Char_u, Char_v, Char_w, Char_x, Char_y, Char_z, Char_LeftBracket,
			Char_BackSlash, Char_RightBracket, Char_Caret, Char__,
			Char_BackQuote, Char_a, Char_b, Char_c, Char_d, Char_e, Char_f,
			Char_g, Char_h, Char_i, Char_j, Char_k, Char_l, Char_m, Char_n,
			Char_o, Char_p, Char_q, Char_r, Char_s, Char_t, Char_u, Char_v,
			Char_w, Char_x, Char_y, Char_z, Char_LeftBrace, Char_VerticalBar,
			Char_RightBrace, Char_Tilde, Char_AfterASCII };
}
